version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: rust:latest
    container_name: urvic-backend-new
    env_file: 
      - .env
    ports:
      - "3001:${APP_PORT}"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}

  mysql:
    image: mysql:8.0
    container_name: urvic-mysql-new
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
