// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `maps_svg` table.
    ///
    /// (Automatically generated by Diesel.)
    maps_svg (id) {
        /// The `id` column of the `maps_svg` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 36]
        id -> Varchar,
        /// The `name` column of the `maps_svg` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `prefix` column of the `maps_svg` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        prefix -> Varchar,
        /// The `content` column of the `maps_svg` table.
        ///
        /// Its SQL type is `Longtext`.
        ///
        /// (Automatically generated by Diesel.)
        content -> Longtext,
        /// The `created_at` column of the `maps_svg` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `updated_at` column of the `maps_svg` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
    }
}

diesel::table! {
    /// Representation of the `products` table.
    ///
    /// (Automatically generated by Diesel.)
    products (id) {
        /// The `id` column of the `products` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        id -> Varchar,
        /// The `product_name` column of the `products` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        product_name -> Nullable<Varchar>,
        /// The `estatus_venta` column of the `products` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        estatus_venta -> Nullable<Varchar>,
        /// The `created_at` column of the `products` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `updated_at` column of the `products` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
    }
}

diesel::table! {
    /// Representation of the `status_colors` table.
    ///
    /// (Automatically generated by Diesel.)
    status_colors (id) {
        /// The `id` column of the `status_colors` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `status_colors` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `status` column of the `status_colors` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        status -> Varchar,
        /// The `hexadecimal` column of the `status_colors` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 7]
        hexadecimal -> Varchar,
        /// The `created_at` column of the `status_colors` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `updated_at` column of the `status_colors` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
    }
}

diesel::table! {
    /// Representation of the `zoho_code` table.
    ///
    /// (Automatically generated by Diesel.)
    zoho_code (id) {
        /// The `id` column of the `zoho_code` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `code` column of the `zoho_code` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        code -> Varchar,
        /// The `created_at` column of the `zoho_code` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `expired_at` column of the `zoho_code` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        expired_at -> Nullable<Timestamp>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(maps_svg, products, status_colors, zoho_code,);
