CREATE TABLE maps_svg (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    prefix VARCHAR(50) NOT NULL,
    content LONGTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

