name: Build for CentOS 7

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libssl-dev pkg-config
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install CentOS 7 compatible target
      run: rustup target add x86_64-unknown-linux-gnu

    - name: Build for CentOS 7
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Upload CentOS 7 binary
      uses: actions/upload-artifact@v3
      with:
        name: urvic-backend-centos7
        path: target/x86_64-unknown-linux-gnu/release/urvic-backend
